### ISSUE TITLE
Base32, Base64 are not RFC4648 compliance!

### ISSUE THREAD

**Issue by fluency03** [multiformats/java-multibase#12] opened 2018-11-14 01:06 UTC
According to [RFC4648](https://tools.ietf.org/html/rfc4648)

- Base 32 Encoding is based on 5-bit group
- Base 64 Encoding is based on 6-bit group

However, the implementations of Base 32 and Base 64 in this project is as same as Base58, which is not correct.

This is also conflict with the specs stated here [multiformats/multibase](https://github.com/multiformats/multibase):

```
encoding      codes   name
identity      0x00    8-bit binary (encoder and decoder keeps data unmodified)
base1         1       unary tends to be 11111
base2         0       binary has 1 and 0
base8         7       highest char in octal
base10        9       highest char in decimal
base16        F, f    highest char in hex
base32        B, b    rfc4648 - no padding - highest letter
base32pad     C, c    rfc4648 - with padding
base32hex     V, v    rfc4648 - no padding - highest char
base32hexpad  T, t    rfc4648 - with padding
base32z       h       z-base-32 - used by Tahoe-LAFS - highest letter
base58flickr  Z       highest char
base58btc     z       highest char
base64        m       rfc4648 - no padding
base64pad     M       rfc4648 - with padding - MIME encoding
base64url     u       rfc4648 - no padding
base64urlpad  U       rfc4648 - with padding
```

**Comment by hohwille** [comment] 2019-05-05 21:56
FYI: If you want something probably more accurate (or to get inspirations to fix from):
https://github.com/m-m-m/binary/tree/master/src/main/java/net/sf/mmm/binary/api/codec

**Comment by ianopolous** [comment] 2019-05-10 10:49
They do use 5 and 6 bit groups. Can you give an example where the encoding is incorrect?

**Comment by tonowie** [comment] 2019-12-15 20:40
I can confirm that Base32 is broken, Base32 indeed is using 5bit groups. Had to swap Base32 implementation for Apache codec to get CID working.... here is example of CID that is Base32 encoded but fails `baegbeibondkkrhxfprzwrlgxxltavqhweh2ylhu4hgo5lxjxpqbpfsw2lu`.

Here is simple jUnit test (`b` being left out of the string)
```
   @Test
   void testBase32() {
      byte[] multibaseBytes = io.ipfs.multibase.Base32.decode("aegbeibondkkrhxfprzwrlgxxltavqhweh2ylhu4hgo5lxjxpqbpfsw2lu");
      byte[] otherBytes = new org.apache.commons.codec.binary.Base32().decode("aegbeibondkkrhxfprzwrlgxxltavqhweh2ylhu4hgo5lxjxpqbpfsw2lu");
      assertArrayEquals(otherBytes, multibaseBytes);
   }
```
That test fails and it is not because Apache got it wrong :)

**Comment by ianopolous** [comment] 2020-07-05 23:37
This is now fixed in master. Thank you.

**Closed by ianopolous** 2020-07-05 23:37 UTC
